# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4a0926a4d655a590763bad0241d85cd7e78c5b6c78f5ddc601fc598b1098cad980f4eed9cf9f046d7cc4cb75c3cc6706a33b805bced5dea05edf1169098b2ab

test:
  secret_key_base: def5ae512da4e72136beecd28529473190bf28c2d5caf0c30c2b144446a0143d4245369ade1fa3e69d092aac9de6deae3bb37b2e2588fa7fc4a9b42075f17f1b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
